<?php
//template was generated by Alchemist - Joomla! module generator, http://alchemist-rad.ru/

/**
 * learn
 * @package mod_learn
 * @version 1.0
 * @author Patrick, <dev@patric.xyz>
 * @link http://patric.xyz
 * @license GNU GPL
 */
defined('_JEXEC') or die;

//Include helper
require_once __DIR__ . '/helper.php';

//Set the config variables
$moduleclass_sfx = $params->get('moduleclass_sfx', null);
$cache = $params->get('cache', '1');
$cache_time = $params->get('cache_time', '900');
$cachemode = $params->get('cachemode', 'static');

//Include CSS
JHtml::stylesheet('mod_learn/style.css', false, true, false);

//Include javascript
JHtml::script('mod_learn/script.js', false, true);

require_once __DIR__ . '/helper.php';

$moduleclass_sfx = htmlspecialchars($params->get('moduleclass_sfx'));

require JModuleHelper::getLayoutPath('mod_learn', $params->get('layout', 'default'));


?>





